[package]
name = "pacman-ostree"
version = "0.1.0"
edition = "2024"

[dependencies]
alpm = "4.0.3"
anyhow = "1.0.100"
camino = "1.2.0"
clap = "4.5.48"
fn-error-context = "0.2.1"
ostree-ext = "0.15.3"
serde = "1.0.227"
serde_yaml = "0.9.34"
tokio = "1.47.1"
